name: flutter_sharez
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ai_barcode_scanner: ^0.0.7
  alfred: ^1.1.1
  auto_route: ^7.8.0
  dart_jwt_token: ^0.0.3
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  duration: ^3.0.13
  file_picker: ^5.3.3
  file_sizes: ^1.0.6
  flash: ^3.0.5+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.3.7
  flutter_speed_dial: ^7.0.0
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  lottie: ^2.6.0
  multiple_result: ^5.1.0
  network_discovery: ^1.0.0
  open_app_file: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  platform_info: ^4.0.2
  qr_flutter: ^4.1.0
  responsive_framework: ^0.2.0
  talker_dio_logger: ^2.3.0
  talker_flutter: ^3.2.9
  velocity_x: ^4.1.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.3
  mocktail: ^1.0.0
  riverpod_lint: ^2.0.1
  riverpod_test: ^0.1.3
  spot: ^0.4.1
  very_good_analysis: ^5.0.0+1






flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo/
    - assets/anim/

